// Core types for the PR Review Agent
import type { GraphReviewContext } from '@agnus-ai/shared'

export interface PullRequest {
  id: string;
  number: number;
  title: string;
  description: string;
  author: Author;
  sourceBranch: string;
  targetBranch: string;
  url: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Author {
  id: string;
  username: string;
  email?: string;
}

export interface Diff {
  files: FileDiff[];
  additions: number;
  deletions: number;
  changedFiles: number;
}

export interface FileDiff {
  path: string;
  oldPath?: string;
  status: 'added' | 'modified' | 'deleted' | 'renamed';
  additions: number;
  deletions: number;
  hunks: DiffHunk[];
}

export interface DiffHunk {
  oldStart: number;
  oldLines: number;
  newStart: number;
  newLines: number;
  content: string;
}

export interface FileInfo {
  path: string;
  content?: string;
  language?: string;
}

export interface ReviewComment {
  id?: string;
  path: string;
  line: number;
  body: string;   // full markdown body generated by the LLM
  severity: 'info' | 'warning' | 'error';
  suggestion?: string;
  confidence?: number;  // 0.0-1.0, self-assessed by LLM
}

export interface Review {
  summary: string;
  comments: ReviewComment[];
  verdict: 'approve' | 'request_changes' | 'comment';
}

export interface Ticket {
  id: string;
  key: string;
  title: string;
  description: string;
  status: string;
  type: string;
  labels: string[];
  acceptanceCriteria?: string[];
}

export interface TicketContext {
  ticket: Ticket;
  relatedPRs: string[];
}

export interface ReviewContext {
  pr: PullRequest;
  diff: Diff;
  files: FileInfo[];
  tickets: Ticket[];
  skills: Skill[];
  config: ReviewConfig;
  graphContext?: GraphReviewContext;
}

export interface ReviewResult {
  summary: string;
  comments: ReviewComment[];
  suggestions: CodeSuggestion[];
  verdict: 'approve' | 'request_changes' | 'comment';
}

export interface CodeSuggestion {
  path: string;
  line: number;
  oldCode: string;
  newCode: string;
  description: string;
}

export interface ReviewConfig {
  maxDiffSize: number;
  focusAreas: string[];
  ignorePaths: string[];
  /** Minimum confidence threshold for comments (0.0–1.0). Default: 0.7 */
  precisionThreshold?: number;
}

export interface Skill {
  name: string;
  description: string;
  triggers: string[];
  priority: 'low' | 'medium' | 'high';
  content: string;
}

export interface Config {
  vcs: {
    github?: {
      token: string;
    };
    azure?: {
      organization: string;
      project: string;
      token: string;
    };
  };
  tickets: TicketConfig[];
  llm: LLMConfig;
  review: ReviewConfig;
  skills: {
    path: string;
    default: string;
  };
}

export interface TicketConfig {
  type: 'jira' | 'linear' | 'github' | 'azure';
  patterns: string[];
  adapter: {
    url?: string;
    token?: string;
    apiKey?: string;
  };
}

export interface LLMConfig {
  // Provider selection: ollama, openai, azure, or custom
  provider: 'ollama' | 'openai' | 'azure' | 'custom';
  // Model ID (provider-specific)
  model: string;
  // Provider-specific configurations
  providers?: {
    ollama?: {
      baseURL?: string;
    };
    openai?: {
      baseURL?: string;
      apiKey?: string;
    };
    azure?: {
      baseURL?: string;
      apiKey?: string;
    };
    custom?: {
      baseURL?: string;
      apiKey?: string;
      headers?: Record<string, string>;
    };
  };
  // Legacy fields for backward compatibility
  baseUrl?: string;
  apiKey?: string;
}

// ============================================
// Incremental Review Checkpoint Types
// ============================================

/**
 * Represents a checkpoint for incremental PR reviews.
 * Stored in a PR comment body as HTML comment metadata.
 */
export interface ReviewCheckpoint {
  /** The SHA of the last reviewed commit */
  sha: string;
  /** Unix timestamp when the checkpoint was created */
  timestamp: number;
  /** List of files that were reviewed */
  filesReviewed: string[];
  /** Number of comments from the last review */
  commentCount: number;
  /** Verdict from the last review */
  verdict: 'approve' | 'request_changes' | 'comment';
}

/**
 * Result of comparing two commits
 */
export interface CommitComparison {
  /** The base commit SHA */
  baseSha: string;
  /** The head commit SHA */
  headSha: string;
  /** Status of the comparison */
  status: 'ahead' | 'behind' | 'diverged' | 'identical';
  /** Number of commits ahead */
  aheadBy: number;
  /** Number of commits behind */
  behindBy: number;
  /** Files changed between base and head */
  files: FileDiff[];
  /** Total additions */
  additions: number;
  /** Total deletions */
  deletions: number;
}

/**
 * Information about a PR comment
 */
export interface PRComment {
  id: number;
  body: string;
  user: {
    login: string;
    type: string;
  };
  createdAt: string;
  updatedAt: string;
}

/**
 * Detailed review comment with position information
 * Used for duplicate detection and line tracking
 */
export interface DetailedReviewComment {
  id: number;
  body: string;
  user: {
    login: string;
    type: string;
  };
  path: string;
  line: number | null;
  originalLine?: number | null;
  position?: number | null;
  commitId?: string;
  inReplyToId?: number | null;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
}

/**
 * Comment metadata stored inline in comments
 * Used for tracking original code and issue context
 */
export interface CommentMetadata {
  /** SHA of the commit when comment was made */
  commitSha: string;
  /** Original code snippet at the line */
  originalCode?: string;
  /** Issue identifier for tracking */
  issueId: string;
  /** Timestamp when comment was created */
  timestamp: number;
}

/**
 * Comment dismissal status
 */
export interface CommentDismissal {
  /** Whether the comment was dismissed */
  dismissed: boolean;
  /** Dismissal reason if any */
  reason?: 'wontfix' | 'as-designed' | 'false-positive' | 'resolved' | 'other';
  /** Who dismissed it */
  dismissedBy?: string;
}

/**
 * File rename information for tracking line movement
 */
export interface FileRename {
  oldPath: string;
  newPath: string;
}

/**
 * Rate limit information
 */
export interface RateLimitInfo {
  limit: number;
  remaining: number;
  resetAt: Date;
  provider: string;
}

/**
 * Review state for tracking
 */
export interface ReviewState {
  prNumber: number;
  lastReviewSha: string;
  lastReviewTime: Date;
  commentCount: number;
  pendingComments: ReviewComment[];
}

/**
 * Idempotency key for preventing duplicate operations
 */
export interface IdempotencyKey {
  key: string;
  createdAt: Date;
  expiresAt: Date;
  operation: 'create_comment' | 'submit_review' | 'create_checkpoint';
}

/**
 * Provider-agnostic PR state
 */
export interface PRState {
  isDraft: boolean;
  isMerged: boolean;
  isClosed: boolean;
  isLocked: boolean;
  mergeable?: boolean;
  mergeableState?: string;
}

/**
 * Secret detection result
 */
export interface SecretDetection {
  found: boolean;
  type?: 'api_key' | 'password' | 'token' | 'private_key' | 'connection_string';
  line?: number;
  path?: string;
  // NOTE: Never include the actual secret value!
}

/**
 * Configuration for comment filtering
 */
export interface CommentFilterConfig {
  maxComments: number;
  maxCommentsPerFile: number;
  maxCommentLength: number;
  skipDrafts: boolean;
  skipMerged: boolean;
  skipClosed: boolean;
  skipLocked: boolean;
  timeout: number;
  retryAttempts: number;
  retryDelay: number;
}

/**
 * Options for incremental review
 */
export interface IncrementalReviewOptions {
  /** Force a full review instead of incremental */
  forceFull?: boolean;
  /** Skip updating the checkpoint after review */
  skipCheckpoint?: boolean;
}
