// Core types for the PR Review Agent

export interface PullRequest {
  id: string;
  number: number;
  title: string;
  description: string;
  author: Author;
  sourceBranch: string;
  targetBranch: string;
  url: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Author {
  id: string;
  username: string;
  email?: string;
}

export interface Diff {
  files: FileDiff[];
  additions: number;
  deletions: number;
  changedFiles: number;
}

export interface FileDiff {
  path: string;
  oldPath?: string;
  status: 'added' | 'modified' | 'deleted' | 'renamed';
  additions: number;
  deletions: number;
  hunks: DiffHunk[];
}

export interface DiffHunk {
  oldStart: number;
  oldLines: number;
  newStart: number;
  newLines: number;
  content: string;
}

export interface FileInfo {
  path: string;
  content?: string;
  language?: string;
}

export interface ReviewComment {
  id?: string;
  path: string;
  line: number;
  body: string;   // full markdown body generated by the LLM
  severity: 'info' | 'warning' | 'error';
  suggestion?: string;
}

export interface Review {
  summary: string;
  comments: ReviewComment[];
  verdict: 'approve' | 'request_changes' | 'comment';
}

export interface Ticket {
  id: string;
  key: string;
  title: string;
  description: string;
  status: string;
  type: string;
  labels: string[];
  acceptanceCriteria?: string[];
}

export interface TicketContext {
  ticket: Ticket;
  relatedPRs: string[];
}

export interface ReviewContext {
  pr: PullRequest;
  diff: Diff;
  files: FileInfo[];
  tickets: Ticket[];
  skills: Skill[];
  config: ReviewConfig;
}

export interface ReviewResult {
  summary: string;
  comments: ReviewComment[];
  suggestions: CodeSuggestion[];
  verdict: 'approve' | 'request_changes' | 'comment';
}

export interface CodeSuggestion {
  path: string;
  line: number;
  oldCode: string;
  newCode: string;
  description: string;
}

export interface ReviewConfig {
  maxDiffSize: number;
  focusAreas: string[];
  ignorePaths: string[];
}

export interface Skill {
  name: string;
  description: string;
  triggers: string[];
  priority: 'low' | 'medium' | 'high';
  content: string;
}

export interface Config {
  vcs: {
    github?: {
      token: string;
    };
    azure?: {
      organization: string;
      project: string;
      token: string;
    };
  };
  tickets: TicketConfig[];
  llm: LLMConfig;
  review: ReviewConfig;
  skills: {
    path: string;
    default: string;
  };
}

export interface TicketConfig {
  type: 'jira' | 'linear' | 'github' | 'azure';
  patterns: string[];
  adapter: {
    url?: string;
    token?: string;
    apiKey?: string;
  };
}

export interface LLMConfig {
  // Provider selection: ollama, openai, azure, or custom
  provider: 'ollama' | 'openai' | 'azure' | 'custom';
  // Model ID (provider-specific)
  model: string;
  // Provider-specific configurations
  providers?: {
    ollama?: {
      baseURL?: string;
    };
    openai?: {
      baseURL?: string;
      apiKey?: string;
    };
    azure?: {
      baseURL?: string;
      apiKey?: string;
    };
    custom?: {
      baseURL?: string;
      apiKey?: string;
      headers?: Record<string, string>;
    };
  };
  // Legacy fields for backward compatibility
  baseUrl?: string;
  apiKey?: string;
}

// ============================================
// Incremental Review Checkpoint Types
// ============================================

/**
 * Represents a checkpoint for incremental PR reviews.
 * Stored in a PR comment body as HTML comment metadata.
 */
export interface ReviewCheckpoint {
  /** The SHA of the last reviewed commit */
  sha: string;
  /** Unix timestamp when the checkpoint was created */
  timestamp: number;
  /** List of files that were reviewed */
  filesReviewed: string[];
  /** Number of comments from the last review */
  commentCount: number;
  /** Verdict from the last review */
  verdict: 'approve' | 'request_changes' | 'comment';
}

/**
 * Result of comparing two commits
 */
export interface CommitComparison {
  /** The base commit SHA */
  baseSha: string;
  /** The head commit SHA */
  headSha: string;
  /** Status of the comparison */
  status: 'ahead' | 'behind' | 'diverged' | 'identical';
  /** Number of commits ahead */
  aheadBy: number;
  /** Number of commits behind */
  behindBy: number;
  /** Files changed between base and head */
  files: FileDiff[];
  /** Total additions */
  additions: number;
  /** Total deletions */
  deletions: number;
}

/**
 * Information about a PR comment
 */
export interface PRComment {
  id: number;
  body: string;
  user: {
    login: string;
    type: string;
  };
  createdAt: string;
  updatedAt: string;
}

/**
 * Options for incremental review
 */
export interface IncrementalReviewOptions {
  /** Force a full review instead of incremental */
  forceFull?: boolean;
  /** Skip updating the checkpoint after review */
  skipCheckpoint?: boolean;
}
